### ISSUE TITLE
.DLL

### ISSUE THREAD

**Issue by AlexanderQueen** [mdilai/Shtreeba#4]
For what purpose is Shreba.DLL? Shreba.exe not enough? Also on inject it crashes. Build in x86 release, W7.

**Comment by mdilai** [comment]
@AlexanderQueen First of all, thanks for bug report, i think i've fixed bug for Windows 7, please pull latest commit and try again.

About your question - basically a whole injector located in Shtreeba.dll library and it can be easily used in some third party projects. Shreeba.exe is just a simple UI interface that load and call injection functions of the library.

I've separated project in two parts because when tried to make monolithic injector it was easily detected as malware DLL injector by dozens of antiviruses and probably VAC. But when separated, each part is harmless - library contains number of routines but don't run anything itself, and UI only call library functions but does not have any own (except process list fetcher) and each part have almost zero detection on VirusTotal. So it's made to confuse antiviruses and anticheats.

**Comment by AlexanderQueen** [comment]
Now it works like a charm. But i find another bug. If you don't set extension .DLL in Shtreeba.ini and only dll name also crashes without notification.

P.S Wanted to ask, it's VAC safe right now, or it need to be re-written a little?

**Comment by mdilai** [comment]
Sure, because it's looking for full absolute or relative path to file to inject. Just remove .dll from cheat's filename and it will not crash 😃

About VAC - i did not tested last few months but i am doubt that Valve added signatures of my modest injector to their bases and pretty sure that only UI theoretically can be detected and in this case it should be rewritten. Fortunately it pretty simple. But i think it safe as is. No guarantees, of course.

**Comment by AlexanderQueen** [comment]
You have discord or telegram?  i  have a few questions.
